# Random Forest Model


In [1]:
from sklearn.preprocessing import StandardScaler 
from sklearn.grid_search import GridSearchCV
import pandas as pd
import numpy as np
import csv
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn import  preprocessing, ensemble
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score, log_loss
import matplotlib.pyplot as plt

In [2]:

df = pd.read_csv('Final_Project_Variables-train.csv',sep = ",", header = 0)
df2 = pd.read_csv('Final_Project_Variables-test.csv',sep = ",", header = 0)
#df2['listing_id'].astype(int)
response = df['interest_code']
#print(response)
listing_id = df["listing_id"]
df = df.drop(df.columns[[0,2]], axis=1)
df2 = df2.drop(df2.columns[[0,2]], axis = 1)
#df2.shape
#df2.head()



In [9]:
X = np.array(df)
y = np.array(response)
print(X.shape)


(49352, 823)


In [10]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.1)
print(X_train.shape)
print(y_train.shape)
print(y_val.shape)
print(X_val.shape)

(44416, 823)
(44416,)
(4936,)
(4936, 823)


In [11]:
X = np.array(df)
#print(X.shape)

X_val2 = np.array(df2)


In [12]:
clf = RFC(n_jobs=-1, n_estimators = 1000, oob_score = True)
clf.fit(X_train, y_train)
y_val_pred = clf.predict_proba(X_val)
log_loss(y_val, y_val_pred)

0.59184905123572018

In [13]:
 print(y_val_pred)

[[ 0.565  0.281  0.154]
 [ 0.886  0.089  0.025]
 [ 0.962  0.033  0.005]
 ..., 
 [ 0.663  0.241  0.096]
 [ 0.448  0.456  0.096]
 [ 0.874  0.109  0.017]]


In [9]:
importances = clf.feature_importances_

std = np.std([tree.feature_importances_ for tree in clf.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

In [16]:
# Print the feature ranking
print("Feature ranking:")

for f in range(X.shape[1]):
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

# Plot the feature importances of the forest
plt.figure()
plt.title("Feature importances")
plt.bar(range(X.shape[1]), importances[indices],
       color="r", yerr=std[indices], align="center")
plt.xticks(range(X.shape[1]), indices)
plt.xlim([-1, X.shape[1]])
plt.show()

Feature ranking:
1. feature 15 (0.010185)
2. feature 14 (0.009183)
3. feature 558 (0.005311)
4. feature 588 (0.005186)
5. feature 587 (0.005180)
6. feature 16 (0.005149)
7. feature 582 (0.004990)
8. feature 579 (0.004989)
9. feature 0 (0.004858)
10. feature 559 (0.004855)
11. feature 581 (0.004805)
12. feature 586 (0.004740)
13. feature 11 (0.004673)
14. feature 578 (0.004672)
15. feature 584 (0.004597)
16. feature 580 (0.004577)
17. feature 583 (0.004549)
18. feature 10 (0.004507)
19. feature 585 (0.004494)
20. feature 576 (0.004450)
21. feature 3 (0.004249)
22. feature 17 (0.004170)
23. feature 577 (0.004153)
24. feature 570 (0.004108)
25. feature 575 (0.003965)
26. feature 572 (0.003940)
27. feature 571 (0.003920)
28. feature 8 (0.003912)
29. feature 573 (0.003837)
30. feature 568 (0.003792)
31. feature 574 (0.003720)
32. feature 498 (0.003693)
33. feature 528 (0.003661)
34. feature 569 (0.003657)
35. feature 567 (0.003591)
36. feature 468 (0.003567)
37. feature 438 (0.003517)
38. f

In [14]:
y_val_pred2 = clf.predict_proba(X_val2)
#log_loss(y_val, y_val_pred2)
df2['listing_id'].astype(int)

0        7142618
1        7210040
2        7174566
3        7191391
4        7171695
5        7225206
6        7200075
7        7145074
8        7193645
9        7147703
10       7182218
11       7132136
12       7130670
13       7151855
14       7158358
15       7221001
16       7100305
17       7096581
18       7177904
19       7122823
20       7183502
21       7170627
22       7154826
23       7155276
24       7126641
25       7096119
26       7197172
27       7189973
28       7123008
29       7146900
          ...   
74629    6883105
74630    6855306
74631    6838009
74632    6872813
74633    6945631
74634    6857039
74635    6912115
74636    6860317
74637    6933426
74638    6854300
74639    6861347
74640    6851904
74641    7339909
74642    6850648
74643    6919964
74644    6830830
74645    6857035
74646    6845466
74647    6875334
74648    6945518
74649    6823696
74650    6894943
74651    6904613
74652    6814215
74653    6831010
74654    6928108
74655    6906674
74656    68979

In [27]:
submission = pd.DataFrame({
        "listing_id": X_val2[:,0],
        "high": y_val_pred2[:,2],
        "medium":y_val_pred2[:,1],
        "low":y_val_pred2[:,0]
    })
    
columnsTitles=["listing_id","high","medium","low"]
submission["listing_id"] = submission['listing_id'].astype(int)
submission=submission.reindex(columns=columnsTitles)
submission.head()
submission.to_csv('submission.csv', index=False)

In [28]:
submission.head()

listing_id   high  medium    low
0     7142618  0.039   0.586  0.375
1     7210040  0.154   0.214  0.632
2     7174566  0.031   0.101  0.868
3     7191391  0.227   0.269  0.504
4     7171695  0.086   0.191  0.723